apiVersion: v1
kind: PersistentVolume
metadata:
  name: notejam-master-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/notejam-master-storage"
