apiVersion: v1
kind: Pod
metadata:
  name: notejam-db-proxy
  labels:
    name: notejam-db-proxy
spec:
  containers:
  - name: notejam-db-proxy
    image: mariadb/maxscale:latest 
    ports:
      - name: rw  
        containerPort: 4008 
      - name: ro 
        containerPort: 4006 
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: maxscale-config
        mountPath: /etc/maxscale.cnf
        subPath: maxscale.cnf
  volumes:
    - name: maxscale-config
      secret:
        secretName: maxscale-config 
