apiVersion: v1
kind: Pod
metadata:
  name: notejam-db-slave-01
  labels:
    repl-role: notejam-db-slave-01
spec:
  containers:
  - name: notejam-db-slave-01
    image: bitnami/mariadb:latest 
    ports:
    - containerPort: 3306
    imagePullPolicy: IfNotPresent
    env:
      - name: MARIADB_REPLICATION_MODE
        value: slave 
      - name: MARIADB_REPLICATION_USER
        valueFrom:
          secretKeyRef:
            name: notejam-db
            key: repl_user
      - name: MARIADB_REPLICATION_PASSWORD
        valueFrom:
          secretKeyRef:
            name: notejam-db
            key: repl_password
      - name: MARIADB_MASTER_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: notejam-db
            key: root_password
      - name: MARIADB_MASTER_HOST
        value: notejam-db-master-svc
    volumeMounts:
      - name: db-slave-01-storage
        mountPath: /bitnami/mariadb
      - name: db-slave-01-cnf
        mountPath: /opt/bitnami/mariadb/conf/bitnami/my_custom.cnf
        subPath: my_custom.cnf
  volumes:
    - name: db-slave-01-cnf
      configMap:
        name: db-slave-01-cnf
    - name: db-slave-01-storage
      persistentVolumeClaim:
        claimName: notejam-db-slave-01-claim
  securityContext:
    fsGroup: 1000
 

