apiVersion: v1
kind: Pod
metadata:
  name: notejam-manage
spec:
  containers:
  - name: notejam-manage
    image: notejam_app:dry_run
    ports:
    - containerPort: 8000
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
    imagePullPolicy: IfNotPresent
    env:
      - name: NJ_DB_USER
        valueFrom:
          secretKeyRef:
            name: notejam-db
            key: username
      - name: NJ_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: notejam-db
            key: password
      - name: NJ_DB_HOST
        value: notejam-db-proxy-svc 
      - name: NJ_DB_PORT
        value: '4008'
    volumeMounts:
      - name: notejam-settings
        mountPath: /opt/notejam/notejam/notejam/settings.py
        subPath: settings.py
  volumes:
    - name: notejam-settings
      configMap:
        name: notejam-settings 
