apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notejam-db-slave-01-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
