apiVersion: v1
kind: Service
metadata:
  name: notejam-db-master-svc 
  labels:
    name: notejam-db-master-svc
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      repl-role: notejam-db-master
