apiVersion: v1
kind: Service
metadata:
  name: notejam-db-proxy-svc 
  labels:
    name: notejam-db-proxy-svc
spec:
  ports:
    - name: rw
      port: 4008 
      targetPort: 4008
    - name: ro
      port: 4006
      targetPort: 4006
  selector:
      name: notejam-db-proxy
